Q.1 Find customers who spent more than the average invoice amount.

SELECT c.customer_id,
       c.first_name,
       c.last_name,
       SUM(i.total) AS total_spent
FROM customer c
JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING SUM(i.total) >
(
SELECT AVG(total)
FROM invoice
)
ORDER BY total_spent DESC;

Q.2 Find the total revenue generated by each employee.

SELECT e.first_name,
       e.last_name,
       SUM(i.total) AS revenue
FROM employee e
JOIN customer c
ON e.employee_id = c.support_rep_id
JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY e.first_name, e.last_name
ORDER BY revenue DESC;

Q.3 Find the total number of tracks purchased by each customer.

SELECT c.customer_id,
       c.first_name,
       c.last_name,
       SUM(il.quantity) AS tracks_purchased
FROM customer c
JOIN invoice i
ON c.customer_id = i.customer_id
JOIN invoice_line il
ON i.invoice_id = il.invoice_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY tracks_purchased DESC;

Q.4 Find the total revenue generated by each country.

SELECT billing_country,
       SUM(total) AS total_revenue
FROM invoice
GROUP BY billing_country
ORDER BY total_revenue DESC;

Q.5 Find the average track price for each genre.

SELECT g.name,
       AVG(t.unit_price) AS average_price
FROM genre g
JOIN track t
ON g.genre_id = t.genre_id
GROUP BY g.name
ORDER BY average_price DESC;

Q.6 Find the total amount spent by each customer.

SELECT c.customer_id,
       c.first_name,
       c.last_name,
       SUM(i.total) AS total_spent
FROM customer c
JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spent DESC;

Q.7 Find artists who have more than 5 albums.   

SELECT ar.name,
       COUNT(alb.album_id) AS total_albums
FROM artist ar
JOIN album alb
ON ar.artist_id = alb.artist_id
GROUP BY ar.name
HAVING COUNT(alb.album_id) > 5
ORDER BY total_albums DESC;

Q.8 Which city has the best customers? We would like to throw a promotional Music Festival in the city we made the most money. 
Write a query that returns one city that has the highest sum of invoice totals. 
Return both the city name & sum of all invoice totals.

SELECT billing_city,SUM(total) AS InvoiceTotal
FROM invoice
GROUP BY billing_city
ORDER BY InvoiceTotal DESC
LIMIT 1;
	
Q.9 Count the number of tracks in each genre.

SELECT g.name AS genre,
       COUNT(t.track_id) AS total_tracks
FROM genre g
JOIN track t
ON g.genre_id = t.genre_id
GROUP BY g.name
ORDER BY total_tracks DESC;

Q.10 Find the number of albums released by each artist.

SELECT ar.name AS artist_name,
       COUNT(alb.album_id) AS total_albums
FROM artist ar
JOIN album alb
ON ar.artist_id = alb.artist_id
GROUP BY ar.name
ORDER BY total_albums DESC;

Q.11 Find customers who have made more than 5 purchases.
	
SELECT c.customer_id,
       c.first_name,
       c.last_name,
       COUNT(i.invoice_id) AS purchases
FROM customer c
JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING COUNT(i.invoice_id) > 5
ORDER BY purchases DESC;

Q.12 Display each album along with its artist name.

SELECT alb.title AS album_name,
       ar.name AS artist_name
FROM album alb
JOIN artist ar
ON alb.artist_id = ar.artist_id;

Q.13 Display every invoice with the customer’s full name.

SELECT i.invoice_id,
       c.first_name,
       c.last_name,
       i.invoice_date,
       i.total
FROM invoice i
JOIN customer c
ON i.customer_id = c.customer_id
ORDER BY i.invoice_date;

Q.14 Find the best-selling artist.

SELECT ar.name AS artist_name,
       SUM(il.unit_price * il.quantity) AS total_sales
FROM invoice_line il
JOIN track t
ON il.track_id = t.track_id
JOIN album alb
ON t.album_id = alb.album_id
JOIN artist ar
ON alb.artist_id = ar.artist_id
GROUP BY ar.name
ORDER BY total_sales DESC
LIMIT 1;

Q.15 Find the best-selling genre.

SELECT g.name AS genre,
       SUM(il.unit_price * il.quantity) AS total_sales
FROM invoice_line il
JOIN track t
ON il.track_id = t.track_id
JOIN genre g
ON t.genre_id = g.genre_id
GROUP BY g.name
ORDER BY total_sales DESC
LIMIT 1;

Q.16 Find artists who generated more than $100 in revenue.

SELECT ar.name,
       SUM(il.unit_price * il.quantity) AS revenue
FROM invoice_line il
JOIN track t
ON il.track_id = t.track_id
JOIN album alb
ON t.album_id = alb.album_id
JOIN artist ar
ON alb.artist_id = ar.artist_id
GROUP BY ar.name
HAVING SUM(il.unit_price * il.quantity) > 100
ORDER BY revenue DESC;

Q.17 Find customers who never made a purchase.

SELECT c.customer_id,
       c.first_name,
       c.last_name
FROM customer c
LEFT JOIN invoice i
ON c.customer_id = i.customer_id
WHERE i.invoice_id IS NULL;

Q.18 Find the most purchased track.

SELECT t.name,
       SUM(il.quantity) AS total_purchases
FROM invoice_line il
JOIN track t
ON il.track_id = t.track_id
GROUP BY t.name
ORDER BY total_purchases DESC
LIMIT 1;

Q.19 Show the top 10 most expensive tracks.

SELECT name, unit_price
FROM track
ORDER BY unit_price DESC
LIMIT 10;

Q.20 Find the number of customers handled by each employee.

SELECT e.employee_id,
       e.first_name,
       e.last_name,
       COUNT(c.customer_id) AS total_customers
FROM employee e
JOIN customer c
ON e.employee_id = c.support_rep_id
GROUP BY e.employee_id, e.first_name, e.last_name
ORDER BY total_customers DESC;

Q.21 Rank customers based on total spending.

SELECT c.customer_id,
       c.first_name,
       c.last_name,
       SUM(i.total) AS total_spent,
       RANK() OVER(ORDER BY SUM(i.total) DESC) AS customer_rank
FROM customer c
JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;

Q.22 Who is the best customer? The customer who has spent the most money will be declared the best customer. 
Write a query that returns the person who has spent the most money.

SELECT customer.customer_id, first_name, last_name, SUM(total) AS total_spending
FROM customer
JOIN invoice ON customer.customer_id = invoice.customer_id
GROUP BY customer.customer_id
ORDER BY total_spending DESC
LIMIT 1;

Q.23 Write query to return the email, first name, last name, & Genre of all Rock Music listeners. 
Return your list ordered alphabetically by email starting with A. 

SELECT DISTINCT email AS Email,first_name AS FirstName, last_name AS LastName, genre.name AS Name
FROM customer
JOIN invoice ON invoice.customer_id = customer.customer_id
JOIN invoiceline ON invoiceline.invoice_id = invoice.invoice_id
JOIN track ON track.track_id = invoiceline.track_id
JOIN genre ON genre.genre_id = track.genre_id
WHERE genre.name LIKE 'Rock'
ORDER BY email;

Q.24 Return all the track names that have a song length longer than the average song length. 
Return the Name and Milliseconds for each track. Order by the song length with the longest songs listed first.

SELECT name,miliseconds
FROM track
WHERE miliseconds > (
	SELECT AVG(miliseconds) AS avg_track_length
	FROM track )
ORDER BY miliseconds DESC;

Q.25 Find artists who have more than 10 tracks.

WITH artist_tracks AS
(
    SELECT ar.name,
           COUNT(t.track_id) AS total_tracks
    FROM artist ar
    JOIN album alb
    ON ar.artist_id = alb.artist_id
    JOIN track t
    ON alb.album_id = t.album_id
    GROUP BY ar.name
)

SELECT *
FROM artist_tracks
WHERE total_tracks > 10
ORDER BY total_tracks DESC;

Q.26 Number customers within each country based on their spending.

SELECT c.country,
       c.first_name,
       c.last_name,
       SUM(i.total) AS total_spent,
       ROW_NUMBER() OVER(
           PARTITION BY c.country
           ORDER BY SUM(i.total) DESC
       ) AS row_num
FROM customer c
JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY c.country, c.customer_id, c.first_name, c.last_name;
	
	
Thank You :) 
